<script>

/*
const arr = [10, 20, 30]// are usinng crlue bases . array of the varailbe using constant
arr[3] = 40

const[a, b,...rest] = arr // rest are using hide the index
console.log(rest) 


//position //assinding order //di assinding order

const arr = [10,70,80]    //push last positon to add 
 arr.pop [40]  // pop shoud be remove the value            /
 arr.push [40] 
  arr.unshift [40]    //unsshift to add first positon  
   arr.unshift [40] 
   arr.shift[4]
   arr.pop()

console.log(arr)


//function    // all the declaration top of the hosting  run the hosting   
function add (){
    console.log('function triggered')
}
add()    // example function code ..




// function parameters..
function greet(name){    // this is parameters function
    console.log("hello"+name);

}
greet("reddy");
greet("gkreddy")



// function return value:

function add(a,b){
    return a+b
}
let sum= add(10,40);  // function are add to the value
console.log(sum)

*/


// array function to add values and addation of the values

const add=(a,b)=> a+b;
console.log(add(5,10));   // this is array function






</script>




