<script>


//math object example

//Math.abs(-7.7); // returns the absolute value of 7.7
//console.log(Math.abs(7.7)); // 7.7



// Math.ceil(7.7); // returns the absolute value of 7.7
// console.log(Math.ceil(7.2)); // 8  up to the nearest integer


// Math.floor(7.7); // returns the absolute value of 7.7
// console.log(Math.floor(7.7)); // 7  down to the nearest integer
// 


//// trunc example//
// Math.trunc(7.6); // returns the absolute value of 7.7    
// console.log(Math.trunc(7.6)); // 7 removes the decimal part


 // round  pooitive  example
 // Math.round(7.5); // returns the absolute value of 7.7
 // console.log(Math.round(7.5)); // 8  rounds to the nearest integer




// negative round example

// Math.round(-7.5); // returns the absolute value of -7.7
// console.log(Math.round(-7.5)); // -7 rounds to the nearest integer




</script>
