Today i was lerning by string methods



<script>
// This is a simple JavaScript code snippet that defines a string variable and logs it to the console.

/*
let str = "Hello  World!";

str.startsWith();

console.log(str.startsWith("Hello"));


/*
let str = "Hello, World!";
let substring =                     // substring this means to extract a part of the string
str.substring(0,4);
console.log(substring);






let str = "Hello, World!";
let substring =                     // substring this means to extract a part of the string
str.substring(-9);
console.log(substring);

// conact method is used to join two or more strings
let str = "Hello, World!";
let str1 = "Good Morning";
let newstr = str.concat(" ",str1);
console.log(newstr);




// this is boolean method it returns true or false
// it is case sensitive

let str = "Hello  World!";

str.startsWith();

console.log(str.startsWith("Hello")); // true
console.log(str.startsWith("hello")); // false

console.log(str.startsWith("lo",3)); // true is formed by the position 3






// this is endsWith method it returns true or false
// it is case sensitive 

let str = "Hello  World!";

str.endsWith();

console.log(str.endsWith("Hello")); // false
console.log(str.endsWith("hello")); // false

console.log(str.endsWith("l",3));  // true is formed by the position 3
console.log(str.endsWith("!")); // true is formed by the position 



// this is replace method it replaces a specified value with another value in a string


str = "Hello, World!";
let newstr = str.replace("W", "g");
console.log(newstr);





// this is  a replaceAll the code replaces all occurrences of a specified value with another value in a string 


str = "Hello, World!";
let newstr = str.replaceAll("good", "JavaScript");
console.log(newstr);



str = "Hello, World!";
let newstr = str.repeat('W',3);

console.log(newstr);
*/







</script>
