<script>


//replace this comment with your code
let text = "Hello World! Hello to JavaScript.";
let nextText = text.replaceAll("Hello","Hi" ); // splits the string into an array of words
console.log(nextText); // ["Hello", "World!", "Welcome", "to", "






// split and join example

//let str = "Hello World!";

//str.split('e '); // splits the string into an array of words
//console.log(str.split('e ')); // ["H", "llo World!"]


//let serachString = "apple,banana,cherry";
//let serachString = "apple,banana,cherry";
//let fruitsArray = serachString.split(','); // splits the string into an array of fruits

//console.log(fruitsArray); // ["apple", "banana", "cherry"]

// join example
//let fruits = ["apple", "banana", "cherry"];
//let fruitsString = fruits.join(', '); // joins the array into a string with ', ' as separator
//console.log(fruitsString); // "apple, banana, cherry"



</script>
