set object some models..



// set object 
<script>


// const  users = { id:1, name:"gopi", age:23, id:10}
// 
// 
// console.log(users.age)   // it will return last id value only 10 because id is repeated
// 

// const arr = [1,2,3,1,2,3]
// 
// 
// const newArr = new Set(arr)   // it will remove duplicates
// newArr.add(4)   // it will add new value
// console.log(newArr) 
// 
// const filterData = arr.map((item) => item )  // it will return all values including duplicates
  // it will return all values including duplicates

// const arr = [1,2,3,1,2,3]
// const newArr = new Set(arr)   // it will remove duplicates
// newArr.delete(3)   // it will delete value 3
// console.log(newArr) 

// const arr = [1,2,3,1,2,3]
// const newArr = new Set(arr)   // it will remove duplicates
// newArr.clear()   // it will clear all values
// console.log(newArr) 

// const arr = [1,2,3,1,2,3]
// const newArr = new Set(arr)   // it will remove duplicates
// newArr.size;  // it will add new value
// console.log(newArr) 



// const arr = [1,2,3,1,2,3]
// const newArr = new Set(arr)   // it will remove duplicates
// newArr.has(1)   // it will check value is present or not
// console.log(newArr) 


 // const arr = [100,200,300,100,200,300]
 // 
 // // add 500 in to the arr
 // arr.push(500)
 // 
 // // remove duplicates for the arr
 // const newSet = new Set(arr)   // it will remove duplicates
 // console.log(newSet)
 // // add 600  value in to the arr
 // arr.push(600)
 // newSet. clear(100)  // it will clear all values
 // newSet. delete(100)    // it will delete value 100              
 // console.log(newSet) 





</script>
