<script>

 //slice example array
 //const arrayofNumbers = [1,2,3,4,5,6,7,8,9,10];
 // arrayofNumbers.slice(2,3); // starting index, ending index (not included)
// console.log(arrayofNumbers);  // unchaged original array

 

//slice example array
// const arrayofNumbers = [1,2,3,4,5,6,7,8,9,10];
// const slicedArray = arrayofNumbers.slice(2,5); // starting index, ending index (not included)        
// console.log(slicedArray);





 // array splice example

// let arrayofNumbers = [1,2,3,4,5,6,7,8,9,10];
//  arrayofNumbers.splice(2,4); // starting index, how many items to remove
// console.log(arrayofNumbers);   



// aray splice example to add items
// let arrayofNumbers = [1,2,3,4,5,6,7 ];
 // arrayofNumbers.splice(2,0,100,200,300); // starting index, how many items to remove, items to add
// console.log(arrayofNumbers);


// array splice example to remove 
//let arrayofNumbers = [1,2,3,4,5,6,7 ];
// arrayofNumbers.splice(2,4); // starting index, how many items to remove
// console.log(arrayofNumbers);



</script>
