<script>

// if condition 

/// let x=10;
/// if(x > 5){
/// 
///     console.log("x is greter than 5");  //10
///    
/// }
/// 


// else if condition
// let age = 18;
// if(age <= 15){
//     console.log("you are eligible for vote");
// } else {
//     console.log("you are not eligible for vote");
// }


// else if condition
// let score = 85;
// if(score <= 90){
//     console.log("A grade");
// } else if(score >= 80){
//     console.log("B grade");
// } else if(score >= 70){
//     console.log("C grade");
// } else {
//     console.log("D grade");
// }


// else if condition
// let marks = 100;
// if(marks <= 80){    
//     console.log("A grade");
// } else if(marks >= 80){
//     console.log("B grade");
// }

// else if condition
let number = 100;
if(number  >= 20){
    console.log("even number");
} else {
    console.log("odd number");
}

</script>
