<script>

 //slice example array
 //const arrayofNumbers = [1,2,3,4,5,6,7,8,9,10];
 // arrayofNumbers.slice(2,3); // starting index, ending index (not included)
// console.log(arrayofNumbers);  // unchaged original array

 

//slice example array
// const arrayofNumbers = [1,2,3,4,5,6,7,8,9,10];
// const slicedArray = arrayofNumbers.slice(2,5); // starting index, ending index (not included)        
// console.log(slicedArray);





 // array splice example

// let arrayofNumbers = [1,2,3,4,5,6,7,8,9,10];
//  arrayofNumbers.splice(2,4); // starting index, how many items to remove
// console.log(arrayofNumbers);   



// aray splice example to add items
// let arrayofNumbers = [1,2,3,4,5,6,7 ];
 // arrayofNumbers.splice(2,0,100,200,300); // starting index, how many items to remove, items to add
// console.log(arrayofNumbers);


// array splice example to remove 
//let arrayofNumbers = [1,2,3,4,5,6,7 ];
// arrayofNumbers.splice(2,4); // starting index, how many items to remove
// console.log(arrayofNumbers);



/   unshift example
   // let arrayofNumbers = [1,2,3,4,5 ];
   // arrayofNumbers.unshift(100,200); // items to add at the beginning array
   // console.log(arrayofNumbers);    

//  shift example
  //let arrayofNumbers = [1,2,3,4,5 ];        
  //  arrayofNumbers.shift(); // removes first item from the array
  //  console.log(arrayofNumbers);  

//  pop example
// let arrayofNumbers = [1,2,3,4,5 ];     
// arrayofNumbers.pop(); // removes last item from the array
// console.log(arrayofNumbers);


//  push example

 let arrayofNumbers = [1,2,3,4,5 ]; 
   
 arrayofNumbers.push(6,7); // adds items at the end of the array

 console.log(arrayofNumbers);



</script>
