<script>

    // non primitativ data types this is using varaibles
/*

const mahObj = {
    m1:99,
    m2:'55'
}

const marksObj = {
    mah:mahObj,
    ph:55,
    ch:66,
}
const stObj = {
     stuId : 10,
     stClass:'10th',   // if you want call only for key names are calling
     stName:'ram', 
    marks:marksObj

}
 //stObj.stName ="gk"  // add the name are upadte the value in data types
   // delete mahObj.m1  // delete this key and values
stObj.email = 'gkreddy@1432'  // add the key and key and values 
console.log(stObj)


*/  // throw consector











</script>
