TODAY IAM LERNING BY A JAVASCRIPT MAIN.JAVASCRIPT AND INCLIND BY A MAIN.HTML

 TODAY BASIC JAVASCRIPT CODE JAVA SCRIPT CODE TO SCRIPT LANGUNAGE

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    
 <script>
   alert('hi');
</script>

 
</head>
<body>
    <p>welcome</p>

   
</body>
</html>
