TODAY I WAS LERNING DATA TYPES IN JAVA SCRIPT

AND OBJECTCLASS AND OBJECT


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
     //concativenation   or template literle
    // let a = 10
     //let b = "20"
    // console.log(a*b)
// data types
    // let a = 100
    // let b =  "10"  // type corresion
      
    // let c = a+b  // let c = a-b .. 90
    // console.log(c)//  result:10010

a = 10
b = 20
a+b
console.log(a+b)

a = 10
b = 20
a+b
console.log(a-b)
a = 10
b = 20
a+b
console.log(a*b)
//string....
a = 10
b = "20" // string using value
a+b
console.log(a+b)


    
//boolean
 a = 10
 b = "true"
 console.log(a+true)


  a = 10
 b = "true"
 console.log(a+true)

a = 9
b = "false"
console.log('a+true')

a = 10
b = "false"
console.log('a+true')


// undefined
//let a = 10
//let b = "undefined"
//console.log(a+b)

//null
//let a = 10
//let b = "null"
//console.log(a+b)


// how to use ==,===
//let a = 10
//let b = 10
//a==b
//console.log(a==b)

//object data types


//const objClass  = {
  //  classId:10,
  //  className:'10th',
  //  stCount:20,
  //  time: 10.30,
//}
// console.log(objClass)

//object
const objClass  = {
    classId:10,
    className:'10th',
    stCount:20,
    time: 10.30
}
objClass.location="hyd"
console.log(objClass)

    </script>
</body>
</html>

