TODAY I WAS LERNING JAVASCRIPT DOT NOTATION AND [] NOTATION JAVASCRIPT AND YOU CAN ACXES  DYANAMIC


<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <script>
    // user object


//const address={
 // street:'ramnagar',
 // suite:'atp'
//}




   // const user ={
   // id : '1',
    //name: 'gk',
   // email : 'gk@gmail.com',  ///dyanmic ga create cheyali and proto type
    //address:address

    //}
//console.log(user)
  
//const firstObj={
//  maths:35,
//  phys:45,
//  chemistry:46,
//
//}
//const secObj={
//  maths:39,
//  phys:40,
//  chemistry:45,
//
//}
//const thirdObj={
//  maths:38,
//  phys:35,
//  chemistry:42,
//
//}
//
//const student={
//  id :'1',
//  name:'ram',
//  first:firstObj,
//  secound:secObj,
//  third:thirdObj,
//
//}
// delete student.secound.phys
//console.log(student.secound)
//student.secound.chemistry=76
 //console.log(student.secound.chemistry)
//object curlibases
//const firstObj={
//  maths:35,
//  phys:45,
//  chemistry:46,
//
//}
//const secObj={
//  maths:39,
//  phys:40,
//  chemistry:45,
//
//}
//
//let semType= 'first'
//const student={
//  id :'1',
//  name:'ram',
//  first:firstObj,
//  secound:secObj,
// 
//
//}
//
//console.log(student[semType].phys)//dot notation
//


//const emp={
//  empId:101,
//  empSal:26000,
//  location:{
//    lat:'12345',
//    lon:'912194'
//  }
//}
//
//
//emp.location.lat  // dot notation
//emp['location'].lat// [] notation
//console.log(emp)
//  dynamic exces
//let user={
//  id:10,
//  name:'gk',
//  age:20
//
//  
//}
//const {id, name, age} = user // you can exces dynamically
//console.log(user)

  </script>
</body>
</html>
