TODAY I AM LERNING BY JAVASCRIPT SMALL CODE...


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width= , initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>

   const address={
    street: 'ram nagar',
    suites:'atp'
   }

  const user = {
    id:1,
    name: 'ram',
    userName:'gk',
    email: 'gk@gmail.com',
    address:address,

  }
  
console.log(user)

    </script>
</body>
</html> 
