TODAY I AM LERNING WHAT IS VAR ,LET,CONST


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>

          

  
    /* this is var mens varailble

    var gk='hello';
    console.log(gk); this is var mens varailble


      console.log(gk);   # THIS IS UNDEFINED BECAUSE VAR IS FUNCTION SCOPE
    var gk='hello';


      var a;  # undefined order
  console.log(gk);

 /* let mens varailble



    let gk='hello';
    console.log(gk);


     console.log(gk1);   # this is a refrence error
      let gk1='hello1';

       let a;  # undefined
  console.log(gk);


*/ const means variables
 const gk='hello';
    console.log(gk);

     const a;  # undefined
  console.log(gk);

  console.log(gk2);   # this is refrence error cont
     const gk2='hello2';


   
    
    
    </script>
</body>
</html>
